name: Snap

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
    - name: Setup LXD
      uses: whywaita/setup-lxd@v1

    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and verify the snap
      env:
        SNAPCRAFT_BUILD_INFO: 1
        SNAP_ENFORCE_RESQUASHFS: 0
      run: |
        sg lxd -c '/snap/bin/snapcraft --use-lxd'

        sudo snap install review-tools
        /snap/bin/review-tools.snap-review *.snap

        echo "::set-output name=snap-file::$( ls *.snap )"

    - name: Upload the snap
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.build-snap.outputs.snap-file }}
        path: ${{ steps.build-snap.outputs.snap-file }}
        if-no-files-found: error
